[CAMERA]
exposure = 40.0
fps = 50.0
num_of_images = 200
kernel_size = [512, 512]

[MOTOR]
controllername = "C-884.DB"
stages = ["M-126.PD2", "M-126.PD2", "M-126.PD2", "NOSTAGE"]
refmodes = ["FNL", "FRF"]
serialnum = "0000000000"

[AXES]
x = 1
y = 3
z = 2

[VERTEX]
pt1 = [2.0, 6.0]
pt2 = [14.0, 14.0]

[MOVEMENT]
dx = 0.3
dy = 0.5
dz = 0.005
min_z = 3.500

[FILE]
save_dir = "frames"
model_path = "models/cell.pt"
